/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.forrestpruitt.texas;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Nater
 */
public class TexasGUI extends javax.swing.JFrame {

    /**
     * Creates new form TexasGUI
     */
	Game game;
	Player player1;
	Player player2;
	boolean isPlayer1Turn;
	
    public TexasGUI(Game game, Player player1, Player player2) {
        this.game = game;
        this.player1 = player1;
        this.player2 = player2;
        initComponents();
    }
    
    public void newGame(Game game)
    {
    	this.game = game;
    	card1of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png"));
    	card2of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png"));
    	card3of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png"));
    	card4of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png"));
    	card5of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png"));
    	lblHand.setVisible(false);
    	cardOpponent1.setIcon(new javax.swing.ImageIcon("images/cardBgBlue.png"));
    	cardOpponent2.setIcon(new javax.swing.ImageIcon("images/cardBgBlue.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	isPlayer1Turn = false;
    	communityCards = new ArrayList<Card>();
        dlgBet = new javax.swing.JDialog();
        betQuestion = new javax.swing.JLabel();
        txtBetAmount = new javax.swing.JTextField();
        btnBetOK = new javax.swing.JButton();
        lblLosses = new javax.swing.JLabel();
        lblWins = new javax.swing.JLabel();
        lblUserBank = new javax.swing.JLabel();
        lblOpponentBet = new javax.swing.JLabel();
        lblOpponentBank = new javax.swing.JLabel();
        lblPot = new javax.swing.JLabel();
        lblUserBet = new javax.swing.JLabel();
        btnFold = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        btnCall = new javax.swing.JButton();
        btnBet = new javax.swing.JButton();
        cardOpponent1 = new javax.swing.JLabel();
        cardOpponent2 = new javax.swing.JLabel();
        card1of5 = new javax.swing.JLabel();
        card2of5 = new javax.swing.JLabel();
        card3of5 = new javax.swing.JLabel();
        card4of5 = new javax.swing.JLabel();
        card5of5 = new javax.swing.JLabel();
        cardUser1 = new javax.swing.JLabel();
        cardUser2 = new javax.swing.JLabel();
        lblYourTurn = new javax.swing.JLabel();
        lblHand = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();
        player1Name = new javax.swing.JLabel();
        player2Name = new javax.swing.JLabel();
        lblPlayer1Blind = new javax.swing.JLabel();
        lblPlayer2Blind = new javax.swing.JLabel();
        lblAmountToCall = new javax.swing.JLabel();
        lblPlayerWins = new javax.swing.JLabel();

        //Set up the Bet Dialog Box
        dlgBet.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgBet.setAlwaysOnTop(false);
        dlgBet.setLocationByPlatform(true);
        dlgBet.setMaximumSize(new java.awt.Dimension(200, 155));
        dlgBet.setMinimumSize(new java.awt.Dimension(200, 155));
        dlgBet.setPreferredSize(new java.awt.Dimension(200, 155));
        dlgBet.setResizable(true);
        betQuestion.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        betQuestion.setText("Please Enter A Bet:");
        txtBetAmount.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtBetAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBetAmountActionPerformed(evt);
            }
        });
        btnBetOK.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnBetOK.setText("OK");
        btnBetOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetOKActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout dlgBetLayout = new javax.swing.GroupLayout(dlgBet.getContentPane());
        dlgBet.getContentPane().setLayout(dlgBetLayout);
        dlgBetLayout.setHorizontalGroup(
            dlgBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBetLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(betQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBetAmount))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgBetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBetOK)
                .addGap(10, 10, 10))
        );
        dlgBetLayout.setVerticalGroup(
            dlgBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(betQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtBetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBetOK, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        ));

        
        //The main GUI window
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Texas Hold 'Em");
        setIconImage(new javax.swing.ImageIcon("images/icon-64x64.png").getImage());
        setMinimumSize(new java.awt.Dimension(695, 530));
        setPreferredSize(new java.awt.Dimension(695, 530));
        setResizable(false);
        getContentPane().setLayout(null);
        

        lblPlayer1Blind.setFont(new java.awt.Font("Calibri", 1, 18));
        lblPlayer1Blind.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayer1Blind.setText("Big Blind");
        lblPlayer1Blind.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblPlayer1Blind);
        lblPlayer1Blind.setBounds(450, 75, 100, 30);
        
        lblPlayer2Blind.setFont(new java.awt.Font("Calibri", 1, 18));
        lblPlayer2Blind.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayer2Blind.setText("Big Blind");
        lblPlayer2Blind.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblPlayer2Blind);
        lblPlayer2Blind.setBounds(450, 410, 100, 30);
        
        
        lblLosses.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblLosses.setForeground(new java.awt.Color(255, 255, 255));
        lblLosses.setText(String.valueOf(player1.getLosses()));
        lblLosses.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblLosses);
        lblLosses.setBounds(100, 30, 30, 30);

        lblWins.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblWins.setForeground(new java.awt.Color(255, 255, 255));
        lblWins.setText(String.valueOf(player1.getWins()));
        getContentPane().add(lblWins);
        lblWins.setBounds(100, 13, 40, 30);
        
        lblUserBank.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblUserBank.setForeground(new java.awt.Color(255, 255, 255));
        lblUserBank.setText(String.valueOf(player1.getNumOfChips()));
        lblUserBank.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblUserBank);
        lblUserBank.setBounds(323, 440, 60, 20);

        lblOpponentBet.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblOpponentBet.setForeground(new java.awt.Color(255, 255, 255));
        lblOpponentBet.setText(String.valueOf(player2.getTotalBetThisRound()));
        getContentPane().add(lblOpponentBet);
        lblOpponentBet.setBounds(510, 43, 70, 20);

        lblOpponentBank.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblOpponentBank.setForeground(new java.awt.Color(255, 255, 255));
        lblOpponentBank.setText(String.valueOf(player2.getNumOfChips()));
        lblOpponentBank.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblOpponentBank);
        lblOpponentBank.setBounds(325, 110, 60, 20);

        lblPot.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblPot.setForeground(new java.awt.Color(255, 255, 255));
        lblPot.setText(String.valueOf(Game.chipsInPot));
        lblPot.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblPot);
        lblPot.setBounds(324, 279, 80, 20);
        
        lblAmountToCall.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAmountToCall.setForeground(new java.awt.Color(255, 255, 255));
        lblAmountToCall.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblAmountToCall);
        lblAmountToCall.setBounds(220, 295, 200, 20);
        lblAmountToCall.setText("Amount to Call: ");
        //lblAmountToCall.setVisible(false);

        lblUserBet.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblUserBet.setForeground(new java.awt.Color(255, 255, 255));
        lblUserBet.setText("0");
        lblUserBet.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblUserBet);
        lblUserBet.setBounds(509, 375, 80, 20);

        btnFold.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnFold.setForeground(new java.awt.Color(0, 51, 255));
        btnFold.setText("FOLD");
        btnFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoldActionPerformed(evt);
            }
        });
        btnFold.setEnabled(false);
        getContentPane().add(btnFold);
        btnFold.setBounds(437, 470, 80, 30);

        
        
        btnCheck.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(0, 51, 255));
        btnCheck.setText("CHECK");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        btnFold.setEnabled(false);
        getContentPane().add(btnCheck);
        btnCheck.setBounds(137, 470, 90, 30);

        btnCall.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCall.setForeground(new java.awt.Color(0, 51, 255));
        btnCall.setText("CALL");
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });
        btnCall.setEnabled(false);
        getContentPane().add(btnCall);
        btnCall.setBounds(251, 470, 70, 30);

        btnBet.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnBet.setForeground(new java.awt.Color(0, 51, 255));
        btnBet.setText("BET");
        btnBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetActionPerformed(evt);
            }
        });
        btnBet.setEnabled(false);
        getContentPane().add(btnBet);
        btnBet.setBounds(345, 470, 70, 30);

        
        cardOpponent1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cardOpponent1.setIcon(new javax.swing.ImageIcon("images/cardBgBlue.png")); // NOI18N
        cardOpponent1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardOpponent1.setAlignmentY(0.0F);
        getContentPane().add(cardOpponent1);
        cardOpponent1.setBounds(255, 9, 71, 100);

        cardOpponent2.setIcon(new javax.swing.ImageIcon("images/cardBgBlue.png")); // NOI18N
        cardOpponent2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(cardOpponent2);
        cardOpponent2.setBounds(343, 9, 71, 100);

        card1of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card1of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png")); // NOI18N
        card1of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card1of5.setAlignmentY(0.0F);
        getContentPane().add(card1of5);
        card1of5.setBounds(124, 166, 72, 100);

        card2of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card2of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png")); // NOI18N
        card2of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card2of5.setAlignmentY(0.0F);
        getContentPane().add(card2of5);
        card2of5.setBounds(211, 166, 72, 100);

        card3of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card3of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png")); // NOI18N
        card3of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card3of5.setAlignmentY(0.0F);
        getContentPane().add(card3of5);
        card3of5.setBounds(298, 166, 72, 100);

        card4of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card4of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png")); // NOI18N
        card4of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card4of5.setAlignmentY(0.0F);
        getContentPane().add(card4of5);
        card4of5.setBounds(385, 166, 72, 100);

        card5of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card5of5.setIcon(new javax.swing.ImageIcon("images/cardBgRed.png")); // NOI18N
        card5of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card5of5.setAlignmentY(0.0F);
        getContentPane().add(card5of5);
        card5of5.setBounds(471, 166, 72, 100);
        

        
        cardUser1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cardUser1.setIcon(new javax.swing.ImageIcon("images/21.png")); // NOI18N
        cardUser1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardUser1.setAlignmentY(0.0F);
        getContentPane().add(cardUser1);
        cardUser1.setBounds(253, 338, 72, 100);
        cardUser1.setVisible(false);
        
        cardUser2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cardUser2.setIcon(new javax.swing.ImageIcon("images/23.png")); // NOI18N
        cardUser2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardUser2.setAlignmentY(0.0F);
        getContentPane().add(cardUser2);
        cardUser2.setBounds(341, 338, 72, 100);
        cardUser2.setVisible(false);

        lblYourTurn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblYourTurn.setForeground(new java.awt.Color(204, 255, 0));
        lblYourTurn.setText(" Your Turn!");
        lblYourTurn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0), 2));
        lblYourTurn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblYourTurn);
        lblYourTurn.setBounds(292, 312, 80, 21);
        lblYourTurn.setVisible(false);

        lblHand.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblHand.setForeground(new java.awt.Color(204, 255, 0));
        lblHand.setText("(Hand Prints Out Here)");
        lblHand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0), 2));
        getContentPane().add(lblHand);
        lblHand.setBounds(550, 203, 130, 30);
        lblHand.setVisible(false);
        

        wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wallpaper.setIcon(new javax.swing.ImageIcon("images/bg.png")); // NOI18N
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, -20, 690, 550);
        
        updateLabels();
        
        

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void doFlop(Card card1, Card card2, Card card3)
    {
    	card1of5.setIcon(new ImageIcon(card1.getURL()));
    	card2of5.setIcon(new ImageIcon(card2.getURL()));
    	card3of5.setIcon(new ImageIcon(card3.getURL()));
    }
    public void doTurn(Card card1)
    {
    	card4of5.setIcon(new ImageIcon(card1.getURL()));
    }
    public void doRiver(Card card1)
    {
    	card5of5.setIcon(new ImageIcon(card1.getURL()));
    }
    
    public void updateLabels()
    {
    	lblLosses.setText(String.valueOf(Driver.player1.getLosses()));
    	lblWins.setText(String.valueOf(Driver.player1.getWins()));
    	lblUserBank.setText(String.valueOf(Driver.player1.getNumOfChips()));
    	lblOpponentBet.setText(String.valueOf(Driver.player2.getTotalBetThisRound()));
    	lblOpponentBank.setText(String.valueOf(Driver.player2.getNumOfChips()));
    	lblPot.setText(String.valueOf(Game.chipsInPot));
    	lblUserBet.setText(String.valueOf(Driver.player1.getTotalBetThisRound()));
    	lblAmountToCall.setText(String.valueOf("Amount to call: "+Driver.amountToCall));
    }
    public void showOpponentsHand(Card card1, Card card2)
    {
    	cardOpponent1.setIcon(new javax.swing.ImageIcon(card1.getURL()));
    	cardOpponent2.setIcon(new javax.swing.ImageIcon(card2.getURL()));
    }
    /**
     * 
     * @param player1
     * @return 0 to continue and add 200 chips, -1 to exit the game.
     */
    public int showPlayerOutOfChips()
    {
    	Object[] options = {"Yes, please", "No, thanks"};
    	int ans = JOptionPane.showOptionDialog(getContentPane(),
				"You have run out of chips. Would you like to add 200 more to keep going?",
				"Add More Chips?",
				JOptionPane.YES_NO_CANCEL_OPTION,
				JOptionPane.QUESTION_MESSAGE,
				null,
				options,
				options[1]);
    	if(ans == 0)
		{
			//Add 200 chips to player 1
			return 0;
			
			//TODO: Add reset code here
			
		}
		else
		{
			return -1;
		}
    }
    
    public int showComputerOutOfChips()
    {
    	Object[] options = {"Yes, please", "No, thanks"};
		int ans = JOptionPane.showOptionDialog(getContentPane(),
				"Your opponent has run out of chips. Would you like to add 200 more to keep going?",
				"Add More Chips?",
				JOptionPane.YES_NO_CANCEL_OPTION,
				JOptionPane.QUESTION_MESSAGE,
				null,
				options,
				options[1]);
		if(ans == 0)
		{
			//Add 200 chips to player 1
			return 0;
			
			//TODO: Add reset code here
			
		}
		else
		{
			return -1;
		}
    }
    
    public int showPlayer1Win()
    {
    	Object[] options = {"Yes, please", "No, thanks"};
    	
    	int ans = JOptionPane.showOptionDialog(getContentPane(),
				"You have won! Would you like to play again?",
				"Play Again?",
				JOptionPane.YES_NO_CANCEL_OPTION,
				JOptionPane.QUESTION_MESSAGE,
				null,
				options,
				options[1]);
		
		if(ans == 0)
		{
			//Player wants to play again
			//TODO Reset Game Code Goes Here
			return 0;
		}
		else
		{
			//Player wants to quit.
			return -1;
    	}
    	
    }
    
    public int showPlayer2Win()
    {
    	Object[] options = {"Yes, please", "No, thanks"};
    	
		int ans = JOptionPane.showOptionDialog(getContentPane(),
		"You have lost. Would you like to play again?",
		"Play Again?",
		JOptionPane.YES_NO_CANCEL_OPTION,
		JOptionPane.QUESTION_MESSAGE,
		null,
		options,
		options[1]);
		
		if(ans == 0)
		{
			return 0;
		}
		else
		{
			return -1;
    	}
    }
    
    public int showTie()
    {
    	Object[] options = {"Yes, please", "No, thanks"};
    	int ans = JOptionPane.showOptionDialog(getContentPane(),
				"You have tied with the computer. Would you like to play again?",
				"Play Again?",
				JOptionPane.YES_NO_CANCEL_OPTION,
				JOptionPane.QUESTION_MESSAGE,
				null,
				options,
				options[1]);
				
				if(ans == 0)
				{
					return 0;
				}
				else
				{
					return -1;
		    	}
    }
   
    
    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        //Preconditions: That it is Player 1 (human player's) turn
    	//				 That there isn't an amount to call.
    	
    	//TODO: Put code here to end user's turn, start computer's turn.
    	updateLabels();
        Driver.endTurn(0);
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallActionPerformed
        //Preconditions: That it is Player 1 (human player's) turn
    	//				 That the amount to call is positive, non-zero.
    	//Code for calling.
		if(Driver.player1.getNumOfChips() > Driver.amountToCall)
		{
			System.out.println(Driver.player1.getName()+" is calling. This adds "+Driver.amountToCall+" to the pot.");
			Driver.player1.betChips(Driver.amountToCall);
		}
		else
		{
			player1.betChips(player1.getNumOfChips());
			player1.setIsAllIn(true);
		}
		SoundPlayer.playSound(SoundPlayer.sound_betting);
		Driver.amountToCall = 0;
		player1.totalBetThisRound = 0;
		btnCall.setEnabled(false);
		updateLabels();
		Driver.endTurn(0);
    }//GEN-LAST:event_btnCallActionPerformed

    private void btnBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetActionPerformed
        //Opens a centered dialog box for the user to input a bet
        dlgBet.setVisible(true);
        dlgBet.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBetActionPerformed

    private void txtBetAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBetAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBetAmountActionPerformed

    private void btnBetOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetOKActionPerformed
        //TODO Could use some error checking here
    	int betAmount = Integer.parseInt(txtBetAmount.getText());

		if(betAmount < Game.SMALL_BLIND)
		{
    		JOptionPane.showMessageDialog(getContentPane(), ("Does not meet minimum bet of "+Game.SMALL_BLIND));
    		txtBetAmount.setText(null);
		}
    	else if(player1.getNumOfChips() < betAmount)
    	{
    		JOptionPane.showMessageDialog(getContentPane(), ("You only have "+player1.getNumOfChips()+" chips!"));
	    	txtBetAmount.setText(null);
	    }
	    else
	    {
	    	player1.betChips(betAmount);
	    	dlgBet.setVisible(false);
	    	updateLabels();
	    	Driver.endTurn(0);
	    }
		
  
    	
    }
    
	/**
	 * 
	 * @param evt The event that spawned this message.
	 * @return 0 if the player wants to play again, -1 if they want to quit.
	 */
    private void btnFoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoldActionPerformed
        //this is how you change the card icons (this code should not stay here) 
        /*card1of5.setIcon(new ImageIcon("images/cardBgRed"));
        card2of5.setIcon(new ImageIcon("images/cardBgRed"));
        card3of5.setIcon(new ImageIcon("images/cardBgRed"));
        card4of5.setIcon(new ImageIcon("images/cardBgRed"));
        card5of5.setIcon(new ImageIcon("images/cardBgRed"));
        */
    	
    	//Custom button text
    	updateLabels();
    	Driver.endTurn(2);
        
    }//GEN-LAST:event_btnFoldActionPerformed
    
    public static javax.swing.JButton btnBet;
    public static javax.swing.JButton btnBetOK;
    public static javax.swing.JButton btnCall;
    public static javax.swing.JButton btnCheck;
    public static javax.swing.JButton btnFold;
    public static javax.swing.JLabel card1of5;
    public static javax.swing.JLabel card2of5;
    public static javax.swing.JLabel card3of5;
    public static javax.swing.JLabel card4of5;
    public static javax.swing.JLabel card5of5;
    public static javax.swing.JLabel cardOpponent1;
    public static javax.swing.JLabel cardOpponent2;
    public static javax.swing.JLabel cardUser1;
    public static javax.swing.JLabel cardUser2;
    public static javax.swing.JLabel lblPlayer1Blind;
    public static javax.swing.JLabel lblPlayer2Blind;
    public static javax.swing.JLabel lblPlayerWins;
    
    public static javax.swing.JDialog dlgBet;
    public static javax.swing.JDialog dlgPlayerName;
    public static javax.swing.JDialog dlgChipStart;
    
    public static javax.swing.JLabel betQuestion;

    public static javax.swing.JLabel lblHand;
    public static javax.swing.JLabel lblLosses;
    public static javax.swing.JLabel lblOpponentBank;
    public static javax.swing.JLabel lblOpponentBet;
    public static javax.swing.JLabel lblPot;
    public static javax.swing.JLabel lblUserBank;
    public static javax.swing.JLabel lblUserBet;
    public static javax.swing.JLabel lblWins;
    public static javax.swing.JLabel lblYourTurn;
    public static javax.swing.JTextField txtBetAmount;
    public static javax.swing.JLabel wallpaper;
    public static javax.swing.JLabel player1Name;
    public static javax.swing.JLabel player2Name;
    public static javax.swing.JLabel lblAmountToCall;
    
    ArrayList<Card> communityCards;
}