/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.forrestpruitt.texas;
import javax.swing.ImageIcon;
/**
 *
 * @author Nater
 */
public class TexasGUI extends javax.swing.JFrame {

    /**
     * Creates new form TexasGUI
     */
    public TexasGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgBet = new javax.swing.JDialog();
        betQuestion = new javax.swing.JLabel();
        txtBetAmount = new javax.swing.JTextField();
        btnBetOK = new javax.swing.JButton();
        lblLosses = new javax.swing.JLabel();
        lblWins = new javax.swing.JLabel();
        lblUserBank = new javax.swing.JLabel();
        lblOpponentBet = new javax.swing.JLabel();
        lblOpponentBank = new javax.swing.JLabel();
        lblPot = new javax.swing.JLabel();
        lblUserBet = new javax.swing.JLabel();
        btnFold = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        btnCall = new javax.swing.JButton();
        btnBet = new javax.swing.JButton();
        cardOpponent1 = new javax.swing.JLabel();
        cardOpponent2 = new javax.swing.JLabel();
        card1of5 = new javax.swing.JLabel();
        card2of5 = new javax.swing.JLabel();
        card3of5 = new javax.swing.JLabel();
        card4of5 = new javax.swing.JLabel();
        card5of5 = new javax.swing.JLabel();
        cardUser1 = new javax.swing.JLabel();
        cardUser2 = new javax.swing.JLabel();
        lblYourTurn = new javax.swing.JLabel();
        lblHand = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();
        player1Name = new javax.swing.JLabel();
        player2Name = new javax.swing.JLabel();

        dlgBet.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgBet.setAlwaysOnTop(true);
        dlgBet.setLocationByPlatform(true);
        dlgBet.setMaximumSize(new java.awt.Dimension(200, 155));
        dlgBet.setMinimumSize(new java.awt.Dimension(200, 155));
        dlgBet.setPreferredSize(new java.awt.Dimension(200, 155));
        dlgBet.setResizable(false);

        betQuestion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        betQuestion.setText("Please Enter A Bet:");

        txtBetAmount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtBetAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBetAmountActionPerformed(evt);
            }
        });

        btnBetOK.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnBetOK.setText("OK");
        btnBetOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgBetLayout = new javax.swing.GroupLayout(dlgBet.getContentPane());
        dlgBet.getContentPane().setLayout(dlgBetLayout);
        dlgBetLayout.setHorizontalGroup(
            dlgBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBetLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(betQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBetAmount))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgBetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBetOK)
                .addGap(66, 66, 66))
        );
        dlgBetLayout.setVerticalGroup(
            dlgBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(betQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtBetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBetOK, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        ));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Texas Hold 'Em");
        setMinimumSize(new java.awt.Dimension(695, 530));
        setPreferredSize(new java.awt.Dimension(695, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        lblLosses.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblLosses.setForeground(new java.awt.Color(255, 255, 255));
        lblLosses.setText("0");
        lblLosses.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblLosses);
        lblLosses.setBounds(100, 30, 30, 30);

        lblWins.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblWins.setForeground(new java.awt.Color(255, 255, 255));
        lblWins.setText("0");
        getContentPane().add(lblWins);
        lblWins.setBounds(100, 13, 40, 30);

        lblUserBank.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblUserBank.setForeground(new java.awt.Color(255, 255, 255));
        lblUserBank.setText("395");
        lblUserBank.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblUserBank);
        lblUserBank.setBounds(323, 440, 60, 20);

        lblOpponentBet.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblOpponentBet.setForeground(new java.awt.Color(255, 255, 255));
        lblOpponentBet.setText("395");
        getContentPane().add(lblOpponentBet);
        lblOpponentBet.setBounds(510, 43, 70, 20);

        lblOpponentBank.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblOpponentBank.setForeground(new java.awt.Color(255, 255, 255));
        lblOpponentBank.setText("395");
        lblOpponentBank.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblOpponentBank);
        lblOpponentBank.setBounds(325, 110, 60, 20);

        lblPot.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblPot.setForeground(new java.awt.Color(255, 255, 255));
        lblPot.setText("395");
        lblPot.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblPot);
        lblPot.setBounds(324, 279, 80, 20);

        lblUserBet.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblUserBet.setForeground(new java.awt.Color(255, 255, 255));
        lblUserBet.setText("395");
        lblUserBet.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblUserBet);
        lblUserBet.setBounds(509, 375, 80, 20);

        btnFold.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnFold.setForeground(new java.awt.Color(0, 51, 255));
        btnFold.setText("FOLD");
        btnFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoldActionPerformed(evt);
            }
        });
        getContentPane().add(btnFold);
        btnFold.setBounds(437, 470, 80, 30);

        btnCheck.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(0, 51, 255));
        btnCheck.setText("CHECK");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheck);
        btnCheck.setBounds(137, 470, 90, 30);

        btnCall.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCall.setForeground(new java.awt.Color(0, 51, 255));
        btnCall.setText("CALL");
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });
        getContentPane().add(btnCall);
        btnCall.setBounds(251, 470, 70, 30);

        btnBet.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnBet.setForeground(new java.awt.Color(0, 51, 255));
        btnBet.setText("BET");
        btnBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetActionPerformed(evt);
            }
        });
        getContentPane().add(btnBet);
        btnBet.setBounds(345, 470, 70, 30);

        cardOpponent1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cardOpponent1.setIcon(new javax.swing.ImageIcon("images/b1fv.png")); // NOI18N
        cardOpponent1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardOpponent1.setAlignmentY(0.0F);
        getContentPane().add(cardOpponent1);
        cardOpponent1.setBounds(255, 9, 71, 100);

        cardOpponent2.setIcon(new javax.swing.ImageIcon("images/b1fv.png")); // NOI18N
        cardOpponent2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(cardOpponent2);
        cardOpponent2.setBounds(343, 9, 71, 100);

        card1of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card1of5.setIcon(new javax.swing.ImageIcon("images/6.png")); // NOI18N
        card1of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card1of5.setAlignmentY(0.0F);
        getContentPane().add(card1of5);
        card1of5.setBounds(124, 166, 72, 100);

        card2of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card2of5.setIcon(new javax.swing.ImageIcon("images/7.png")); // NOI18N
        card2of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card2of5.setAlignmentY(0.0F);
        getContentPane().add(card2of5);
        card2of5.setBounds(211, 166, 72, 100);

        card3of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card3of5.setIcon(new javax.swing.ImageIcon("images/8.png")); // NOI18N
        card3of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card3of5.setAlignmentY(0.0F);
        getContentPane().add(card3of5);
        card3of5.setBounds(298, 166, 72, 100);

        card4of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card4of5.setIcon(new javax.swing.ImageIcon("images/9.png")); // NOI18N
        card4of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card4of5.setAlignmentY(0.0F);
        getContentPane().add(card4of5);
        card4of5.setBounds(385, 166, 72, 100);

        card5of5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        card5of5.setIcon(new javax.swing.ImageIcon("images/5.png")); // NOI18N
        card5of5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        card5of5.setAlignmentY(0.0F);
        getContentPane().add(card5of5);
        card5of5.setBounds(471, 166, 72, 100);

        cardUser1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cardUser1.setIcon(new javax.swing.ImageIcon("images/21.png")); // NOI18N
        cardUser1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardUser1.setAlignmentY(0.0F);
        getContentPane().add(cardUser1);
        cardUser1.setBounds(253, 338, 72, 100);

        cardUser2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cardUser2.setIcon(new javax.swing.ImageIcon("images/23.png")); // NOI18N
        cardUser2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cardUser2.setAlignmentY(0.0F);
        getContentPane().add(cardUser2);
        cardUser2.setBounds(341, 338, 72, 100);

        lblYourTurn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblYourTurn.setForeground(new java.awt.Color(204, 255, 0));
        lblYourTurn.setText("  Your Turn!");
        lblYourTurn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0), 2));
        lblYourTurn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblYourTurn);
        lblYourTurn.setBounds(292, 310, 80, 21);

        lblHand.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblHand.setForeground(new java.awt.Color(204, 255, 0));
        lblHand.setText(" Straight Royal Flush!");
        lblHand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0), 2));
        getContentPane().add(lblHand);
        lblHand.setBounds(550, 203, 130, 30);

        wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        wallpaper.setIcon(new javax.swing.ImageIcon("images/bg.png")); // NOI18N
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, -20, 690, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoldActionPerformed
        //this is how you change the card icons (this code should not stay here) 
        card1of5.setIcon(new ImageIcon("images/10.png"));
        card2of5.setIcon(new ImageIcon("images/20.png"));
        card3of5.setIcon(new ImageIcon("images/30.png"));
        card4of5.setIcon(new ImageIcon("images/40.png"));
        card5of5.setIcon(new ImageIcon("images/50.png"));
        
    }//GEN-LAST:event_btnFoldActionPerformed

    public void startGame(Player player1, Player player2)
    {
    	card1of5.setVisible(false);
    	card2of5.setVisible(false);
    	card3of5.setVisible(false);
    	card4of5.setVisible(false);
    	card5of5.setVisible(false);
        cardUser1.setVisible(false);
        cardUser2.setVisible(false);
        lblUserBank.setVisible(false);
        lblHand.setVisible(false);
        
        lblUserBank.setText(String.valueOf(player1.getNumOfChips()));
        lblUserBank.setText(String.valueOf(player1.getNumOfChips()));
    	
    }
    
    public void doFlop(Card card1, Card card2, Card card3)
    {
    	card1of5.setIcon(new ImageIcon(card1.getURL()));
    	card2of5.setIcon(new ImageIcon(card2.getURL()));
    	card3of5.setIcon(new ImageIcon(card3.getURL()));
    }
    public void doTurn(Card card1)
    {
    	card4of5.setIcon(new ImageIcon(card1.getURL()));
    }
    public void doRiver(Card card1)
    {
    	card5of5.setIcon(new ImageIcon(card1.getURL()));
    }
    
    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        //This is how you toggle these labels on/off
        lblYourTurn.setVisible(true);
        lblHand.setVisible(true);
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCallActionPerformed
        //This is how you toggle these labels on/off
        lblYourTurn.setVisible(false);
        lblHand.setVisible(false);
    }//GEN-LAST:event_btnCallActionPerformed

    private void btnBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetActionPerformed
        //Opens a centered dialog box for the user to input a bet
        dlgBet.setVisible(true);
        dlgBet.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBetActionPerformed

    private void txtBetAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBetAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBetAmountActionPerformed

    private void btnBetOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetOKActionPerformed
       /*
        * Very important: Since you cannot place an int into the text of a label,
        * you have to place a string in it every time. The time when you take
        * the string value OUT of the label to do a calculation (e.g. add a bet
        * amount to the pot) if when you must force the text to an int using this line of code:
        * int betAmount = Integer.parseInt(txtBetAmount.getText());
        */
        
        /*This example code shows how, when you click the OK button, to take a
         * string from a text box and replace the text on a label elsewhere on
         * the GUI. It then clears the string from the original text box and
         * hides the window until next use.
         * 
        */
        String betAmount = txtBetAmount.getText();
        lblPot.setText(betAmount);
        txtBetAmount.setText(null);
        dlgBet.hide();
    }//GEN-LAST:event_btnBetOKActionPerformed

    public javax.swing.JButton btnBet;
    public javax.swing.JButton btnBetOK;
    public javax.swing.JButton btnCall;
    public javax.swing.JButton btnCheck;
    public javax.swing.JButton btnFold;
    public javax.swing.JLabel card1of5;
    public javax.swing.JLabel card2of5;
    public javax.swing.JLabel card3of5;
    public javax.swing.JLabel card4of5;
    public javax.swing.JLabel card5of5;
    public javax.swing.JLabel cardOpponent1;
    public javax.swing.JLabel cardOpponent2;
    public javax.swing.JLabel cardUser1;
    public javax.swing.JLabel cardUser2;
    
    public javax.swing.JDialog dlgBet;
    public javax.swing.JDialog dlgPlayerName;
    public javax.swing.JDialog dlgChipStart;
    
    public javax.swing.JLabel betQuestion;

    public javax.swing.JLabel lblHand;
    public javax.swing.JLabel lblLosses;
    public javax.swing.JLabel lblOpponentBank;
    public javax.swing.JLabel lblOpponentBet;
    public javax.swing.JLabel lblPot;
    public javax.swing.JLabel lblUserBank;
    public javax.swing.JLabel lblUserBet;
    public javax.swing.JLabel lblWins;
    public javax.swing.JLabel lblYourTurn;
    public javax.swing.JTextField txtBetAmount;
    public javax.swing.JLabel wallpaper;
    public javax.swing.JLabel player1Name;
    public javax.swing.JLabel player2Name;
}